<a href="https://colab.research.google.com/github/ndcastillo/inferential-statistics-DS-AI/blob/main/Funciones_de_Muestreo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cargamos las librerias necesarias para realizar el an√°lisis.

In [ ]:
import pandas as pd
import numpy  as np
import random
import io

Leemos la base de datos a trabajar en nuestra ruta de origen.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Econdata.csv to Econdata.csv

In [ ]:
econdata = pd.read_csv(io.BytesIO(uploaded["Econdata.csv"]))
# Los 5 primeros registros
econdata.head()

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
0,0,"19.424781053,-99.1327537959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1332...",307_130_11,Cuauht√©moc,B,Mercado,Pino Su√°rez
1,1,"19.4346139576,-99.1413808393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_008_01,Cuaut√©moc,A,Museo,Museo Nacional de Arquitectura Palacio de Bell...
2,2,"19.4340695945,-99.1306348409","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_002_12,Cuaut√©moc,A,Museo,Santa Teresa
3,3,"19.42489472,-99.12073393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_102_06,Venustiano Carranza,B,Hotel,Balbuena
4,4,"19.42358238,-99.12451093","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_115_12,Venustiano Carranza,B,Hotel,real

## Funcion de Muestreo

## Muestreo Aleatorio Simple

In [ ]:
aleat_8 = econdata.sample(n=8)
aleat_8

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
97,97,"19.4440005647,-99.1372278043","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_038_04,Cuaut√©moc,B,Museo,Galeria El Tr√©bol
31,31,"19.4242639147,-99.1311619613","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",307_129_20,Cuaut√©moc,B,Hotel,Escorial
57,57,"19.4303913751,-99.1465372648","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_048_10,Cuaut√©moc,B,Hotel,Conde
121,121,"19.4303083246,-99.1405735286","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",001_043_15,Cuaut√©moc,A,Hotel,El Salvador
154,154,"19.4245820084,-99.1259208824","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",307_119_06,Cuaut√©moc,B,Hotel,Las Vegas
186,186,"19.4275038262,-99.1346778267","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_052_24,Cuaut√©moc,A,Museo,Casa de la Memoria Ind√≥mita
38,38,"19.4439555857,-99.1345196425","{""type"": ""Polygon"", ""coordinates"": [[[-99.1351...",004_106_01,Cuauht√©moc,B,Mercado,La Lagunilla Comestibles
76,76,"19.4367072434,-99.1424407474","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_095_02,Cuaut√©moc,A,Museo,Franz Mayer

In [ ]:
aleat_8_2 = econdata.sample(n=8)
aleat_8_2

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
210,210,"19.43082385,-99.12366058","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_029_08,Venustiano Carranza,B,Hotel,Hispano
60,60,"19.4274816595,-99.1285626779","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",006_086_10,Cuaut√©moc,A,Hotel,Oviedo
186,186,"19.4275038262,-99.1346778267","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_052_24,Cuaut√©moc,A,Museo,Casa de la Memoria Ind√≥mita
125,125,"19.4342350395,-99.1354548065","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_007_06,Cuaut√©moc,A,Hotel,Zamora
21,21,"19.43614459,-99.13945267","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_098_01,Cuaut√©moc,A,Museo,Tel√©grafo
120,120,"19.438089976,-99.1374885065","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",004_086_24,Cuaut√©moc,A,Hotel,"Atlanta, S. DE R.L."
154,154,"19.4245820084,-99.1259208824","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",307_119_06,Cuaut√©moc,B,Hotel,Las Vegas
149,149,"19.43031663,-99.12465191","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_035_01,Venustiano Carranza,B,Hotel,Liverpool

In [ ]:
prop_25 = econdata.sample(frac=.25)
print('Dataframe de longitud de '+str(len(prop_25)))

prop_25.head()

Dataframe de longitud de 58

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
135,135,"19.4300009578,-99.1430773295","{""type"": ""Polygon"", ""coordinates"": [[[-99.1431...",002_045_01,Cuauht√©moc,B,Mercado,"Centro Artesanal ""San Juan"""
61,61,"19.4343847692,-99.125125489","{""type"": ""Polygon"", ""coordinates"": [[[-99.1257...",005_140_01,Cuauht√©moc,B,Mercado,Mixcalco
226,226,"19.4416748524,-99.1365878489","{""type"": ""Polygon"", ""coordinates"": [[[-99.1370...",004_052_01,Cuauht√©moc,B,Mercado,De Muebles
190,190,"19.43311885,-99.14512643","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_019_02,Cuaut√©moc,B,Hotel,Metropol
99,99,"19.4438918423,-99.1402516182","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_052_18,Cuaut√©moc,B,Hotel,Drigales

## Muestreo Sistematico

In [ ]:
def systematic_sampling(econdata,step):
  indexes = np.arange(0,len(econdata),step=step)
  systematic_sample = econdata.iloc[indexes]
  return systematic_sample

systematic_sample = systematic_sampling(econdata, 3)
print('El datafame con muestreo sistematico tiene una longitud de '+str(len(systematic_sample)))
systematic_sample.head()

El datafame con muestreo sistematico tiene una longitud de 77

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id
0,0,"19.424781053,-99.1327537959","{""type"": ""Polygon"", ""coordinates"": [[[-99.1332...",307_130_11,Cuauht√©moc,B,Mercado,Pino Su√°rez
3,3,"19.42489472,-99.12073393","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",323_102_06,Venustiano Carranza,B,Hotel,Balbuena
6,6,"19.43553422,-99.12324801","{""type"": ""MultiPoint"", ""coordinates"": [[-99.12...",318_116_11,Venustiano Carranza,B,Hotel,San Antonio Tomatlan
9,9,"19.4407152937,-99.1498060057","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",012_146_22,Cuaut√©moc,B,Hotel,Detroit
12,12,"19.43990186,-99.14813347","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_079_16,Cuaut√©moc,B,Hotel,La Paz

## Muestreo Estratificado

In [ ]:
econdata['estratificado'] = econdata['delegacion']+","+econdata['tipo']
(econdata['estratificado'].value_counts()/len(econdata)).sort_values(ascending=False)

0             Cuauht√©moc,Mercado
1                Cuaut√©moc,Museo
2                Cuaut√©moc,Museo
3      Venustiano Carranza,Hotel
4      Venustiano Carranza,Hotel
                 ...
225    Venustiano Carranza,Hotel
226           Cuauht√©moc,Mercado
227           Cuauht√©moc,Mercado
228              Cuaut√©moc,Museo
229              Cuaut√©moc,Museo
Name: estratificado, Length: 230, dtype: object

Cuaut√©moc,Hotel                0.643478
Cuaut√©moc,Museo                0.156522
Venustiano Carranza,Hotel      0.078261
Cuauht√©moc,Mercado             0.073913
Venustiano Carranza,Mercado    0.047826
Name: estratificado, dtype: float64

Nuestros datos dicen que la proporci√≥n es la siguiente:

1) Hoteles en Cuauhtemoc es el 0.5

2) Los Museos en Cuauhtemoc es el 0.2

3) Hoteles en Venustiano Carranza  es del 0.1

4) Mercados en Cuauhtemoc 0.1

5) Mercados en Venustiano Carranza son el 0.1

In [ ]:
def data_estratificada(econdata,nombres_columnas_estrat, valores_estrat, prop_estrat, random_state=None):

  df_estrat = pd.DataFrame(columns = econdata.columns)

  pos = -1
  for i in range(len(valores_estrat)):
    pos += 1
    if pos == len(valores_estrat) - 1:
      ratio_len = len(econdata) - len(df_estrat)
    else:
      ratio_len = int(len(econdata) * prop_estrat[i])
  
    df_filtrado = econdata[econdata[nombres_columnas_estrat] == valores_estrat[i]]
    df_temp = df_filtrado.sample(replace=True, n=ratio_len, random_state=random_state)
    
    df_estrat = pd.concat([df_estrat, df_temp])
  
  return df_estrat

valores_estrat = ['Cuaut√©moc,Hotel', 'Cuaut√©moc,Museo', 'Venustiano Carranza,Hotel', 'Cuauht√©moc,Mercado','Venustiano Carranza,Mercado']
prop_estrat = [0.5, 0.2, 0.1, 0.1, 0.1]
df_estrat = data_estratificada(econdata, 'estratificado', valores_estrat, prop_estrat, random_state=42)
df_estrat

,id,geo_point_2d,geo_shape,clave_cat,delegacion,perimetro,tipo,nom_id,estratificado
164,164,"19.4388741511,-99.1413308257","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",003_113_03,Cuaut√©moc,B,Hotel,Dos Naciones,"Cuaut√©moc,Hotel"
142,142,"19.4263681354,-99.1327278126","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",006_127_14,Cuaut√©moc,A,Hotel,Ambar,"Cuaut√©moc,Hotel"
27,27,"19.4348360773,-99.1463945583","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_016_01,Cuaut√©moc,B,Hotel,Hilton Centro Hist√≥rico,"Cuaut√©moc,Hotel"
168,168,"19.4349726565,-99.147766133","{""type"": ""MultiPoint"", ""coordinates"": [[-99.14...",002_014_23,Cuaut√©moc,B,Hotel,One Alameda,"Cuaut√©moc,Hotel"
113,113,"19.43374405,-99.13550135","{""type"": ""MultiPoint"", ""coordinates"": [[-99.13...",001_012_13,Cuaut√©moc,A,Hotel,San Antonio,"Cuaut√©moc,Hotel"
...,...,...,...,...,...,...,...,...,...
128,128,"19.4270781084,-99.1210175514","{""type"": ""Polygon"", ""coordinates"": [[[-99.1214...",323_061_04(123),Venustiano Carranza,B,Mercado,San Ciprian,"Venustiano Carranza,Mercado"
37,37,"19.4271233834,-99.125111772","{""type"": ""Polygon"", ""coordinates"": [[[-99.1251...",323_065_01,Venustiano Carranza,B,Mercado,Dulceria,"Venustiano Carranza,Mercado"
163,163,"19.4265454033,-99.1224859032","{""type"": ""Polygon"", ""coordinates"": [[[-99.1231...",323_063_05,Venustiano Carranza,B,Mercado,NaN,"Venustiano Carranza,Mercado"
156,156,"19.4255480371,-99.1249308096","{""type"": ""Polygon"", ""coordinates"": [[[-99.1253...",323_138_04 (3),Venustiano Carranza,B,Mercado,Mariscos,"Venustiano Carranza,Mercado"
37,37,"19.4271233834,-99.125111772","{""type"": ""Polygon"", ""coordinates"": [[[-99.1251...",323_065_01,Venustiano Carranza,B,Mercado,Dulceria,"Venustiano Carranza,Mercado"